apiVersion: v1
kind: Service
metadata:
  name: fitness-tracker-service
  namespace: fitness-prod
spec:
  type: LoadBalancer
  selector:
    app: fitness-tracker
  ports:
  - port: 80
    targetPort: 5000
