apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: fitness-prod
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017