apiVersion: v1
kind: Secret
metadata:
  name: fitness-secret
  namespace: fitness-prod
type: Opaque
stringData:
  MONGODB_URI: "mongodb://mongodb-service:27017/fitness-tracker"
  JWT_SECRET: "change-this-secret-in-production"